import Link from 'next/link';
import { ArrowLeft, ArrowUpRight } from '@phosphor-icons/react/dist/ssr';
import { EntryMark } from './entry-mark';
import { Reveal } from './reveal';
import type { PortfolioEntry } from '@/content/portfolio';

export function EntryDetail({ entry, kind, others }: { entry: PortfolioEntry; kind: 'experience' | 'projects'; others: PortfolioEntry[] }) {
  const project = kind === 'projects';
  return <main id="main" className="shell detail-page"><Link className="back-link" href={project ? '/' : '/#experience'}><ArrowLeft size={17} />{project ? 'Back to portfolio' : 'All experience'}</Link><Reveal><div className="detail-heading"><div><p className="detail-category">{entry.category}{entry.sample && ' · Sample project'}</p><h1>{project ? entry.title : entry.organization}</h1><p className="detail-subtitle">{project ? entry.summary : entry.title}</p></div><div className="detail-mark"><EntryMark slug={entry.slug} large /></div></div></Reveal><div className="detail-meta"><span>{project ? 'Project' : 'Role'}<strong>{entry.title}</strong></span><span>Focus<strong>{entry.category}</strong></span>{entry.date && <span>Dates<strong>{entry.date}</strong></span>}</div><Reveal className="detail-body"><div className="detail-side">{project ? 'The work' : 'Overview'}</div><article><h2>{project ? 'The question and the process' : 'A little about the role'}</h2>{entry.paragraphs.map(p => <p key={p}>{p}</p>)}<div className="detail-empty"><h3>{project ? 'The story is coming together.' : 'More of the story, soon.'}</h3><p>{project ? 'This is a sample project page. The research question, approach, images, and links will be added as we put the portfolio together.' : 'Notes, contributions, and work that can be shared publicly will be added here.'}</p></div>{entry.links.length > 0 && <div className="detail-links">{entry.links.map(link => <a className="text-link" href={link.href} key={link.href}>{link.label}<ArrowUpRight size={17} /></a>)}</div>}</article></Reveal><section className="related-entries"><h2>{project ? 'More work' : 'Other experience'}</h2>{others.map(item => <Link href={`/${kind}/${item.slug}`} key={item.slug}><span>{project ? item.title : item.organization}</span><ArrowUpRight size={20} /></Link>)}</section></main>;
}
